
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[228] =
    {   0,
       77,   77,   74,   74,    0,    0,   80,   78,   77,   60,
       61,   78,   49,   50,   46,   48,   54,   53,   38,   42,
       57,   51,   47,   56,   47,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   58,   59,   78,   73,   74,   75,   76,   71,
       63,   62,   79,   77,    0,    0,   52,    0,   39,    0,
        0,    0,    0,    0,   42,   42,   55,   47,   37,   37,
       37,    0,   37,   37,   37,   37,   37,   27,   37,   37,
       37,   37,   37,   16,   36,   37,   37,    7,   31,   37,
       37,   37,   37,   22,   37,   37,   37,   37,   37,   37,

       37,   74,   71,   72,   70,   69,   67,   64,   68,   65,
       66,   45,    0,    0,   39,   39,   39,   39,   43,    0,
       38,   38,   41,    0,   44,   39,    0,   35,   37,   37,
       37,   37,   37,   33,   37,   37,   19,   37,   13,   37,
       37,   34,   32,   37,   37,   37,    6,   37,   37,   37,
       11,   37,   37,   37,    0,   38,   38,   39,   39,   40,
       43,   38,   38,   38,   41,   44,    0,   37,   37,   37,
        4,   37,   37,   20,   37,   37,   37,   37,   37,   37,
       10,    9,   37,   21,   29,   23,   37,   26,   37,   38,
       38,   38,   40,    0,    0,    5,   18,   37,    3,   37,

       30,   37,   37,   37,   37,   37,   37,   25,   24,   37,
       28,   37,   37,   37,   37,   37,    8,   17,   12,   37,
       15,   37,    1,   14,   37,    2,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   31,   32,   33,   34,   35,   36,
       31,   37,   38,   39,   40,   41,   42,   31,   43,   31,
       44,   45,   46,    1,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   31,   31,   57,   58,   59,
       60,   61,   31,   62,   63,   64,   65,   66,   67,   31,
       68,   31,   69,    1,   70,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    6,    6,    1,    1,    1,    1,
        1,    7,    7,    7,    7,    7,    8,    9,    9,    9,
        9,    9,    9,   10,    9,    9,   10,    9,   10,    9,
       10,    9,    9,    1,    3,    1,   11,    7,    7,    7,
        7,    7,    8,    9,    9,    9,    9,    9,   10,    9,
        9,   10,    9,   10,    9,   10,    9,    9,    1,   12
    } ;

static yyconst flex_uint16_t yy_base[241] =
    {   0,
        0,    0,   68,   69,   70,   72,  582,  692,  579,  692,
      692,  534,  692,  692,  692,  692,  692,   65,   70,   71,
      558,  692,   68,  692,  557,   67,   81,   77,  100,  102,
      105,  528,  116,   43,  107,  121,   47,   66,  125,  144,
       73,  155,  692,  692,    0,  692,    0,  692,  692,    0,
      692,  692,  215,  572,  568,  567,  692,   79,  174,  179,
      556,  205,   86,  182,  213,  218,  692,  692,  522,  184,
      139,  520,  194,  211,  160,  203,  206,  213,  108,  236,
      219,  220,  239,  519,  176,  238,  245,  518,  516,  243,
      269,  249,  268,  491,  257,  263,  264,  265,  261,  276,

      490,    0,    0,  692,  692,  692,  692,  692,  692,  692,
      692,  692,  530,  319,  322,  325,  692,  328,   96,  331,
      692,  338,    0,  521,  519,  217,  341,  420,  328,  331,
      326,  322,  325,  416,  332,  334,  387,  333,  260,  343,
      342,  376,  353,  371,  360,  362,  323,  367,  356,  372,
      315,  373,  381,  365,  417,  692,  423,  426,  429,  350,
      401,  692,  432,  435,    0,  337,  438,  359,  421,  409,
      284,  418,  419,  282,  434,  437,  423,  441,  445,  442,
      271,  267,  454,  258,  228,  212,  446,  198,  447,  692,
      460,  491,  463,  494,  497,  189,  177,  474,  166,  467,

      158,  478,  470,  477,  494,  496,  503,  156,  133,  500,
      131,  505,  501,  495,  511,  506,  119,  117,  115,  521,
      110,  523,   97,   55,  536,   44,  692,  588,  600,  612,
      619,  624,  634,  645,  657,  666,  672,  675,  679,  683
    } ;

static yyconst flex_int16_t yy_def[241] =
    {   0,
      227,    1,  228,  228,  229,  229,  227,  227,  227,  227,
      227,  230,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  227,  227,  232,  227,  233,  227,  227,  234,
      227,  227,  235,  227,  227,  236,  227,  227,  227,  227,
      227,  227,  237,  227,  227,  227,  227,  227,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  233,  234,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  238,  239,  240,  227,  227,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  238,  240,  227,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  227,
      227,  227,  227,  227,  227,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,    0,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227
    } ;

static yyconst flex_uint16_t yy_nxt[763] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       16,   18,   15,   19,   20,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   33,
       32,   32,   34,   35,   36,   37,   38,   39,   40,   32,
       41,   42,   32,   43,    8,   44,   45,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   32,   34,   35,   36,
       37,   38,   39,   40,   32,   41,   42,   32,   46,    8,
       48,   48,   51,   52,   51,   52,   57,   86,   58,   59,
       59,   60,   64,   90,   65,   66,   66,   68,   68,   72,
       72,   91,   61,   72,   97,   62,   62,  123,   63,  124,

       70,   72,   86,   71,  114,   75,   73,  160,   90,  161,
      161,   76,   72,   72,   53,   74,   53,   91,   61,   72,
       97,   62,   62,   72,   63,   70,   81,   72,   71,   77,
      114,   75,   73,   79,   78,   80,   76,   49,   49,   82,
       74,   87,   84,   72,   83,  136,   72,   88,   72,   85,
       92,   72,   81,   72,   72,   77,   72,   89,   79,   78,
       80,   72,   72,   72,   82,   72,   87,   72,   84,   83,
      136,   72,   93,   88,   85,  129,   92,   72,   94,   72,
       95,  132,   89,   98,   99,   72,   96,  115,  116,  116,
       72,  100,  117,  118,  118,  126,   59,   59,   93,  114,

      129,   72,   72,   94,   72,   95,   72,  132,  128,   98,
       99,   96,   72,  120,  141,  120,  100,  105,  121,  122,
      122,  130,   72,   72,  127,  114,   65,   65,   65,   64,
       72,   65,   66,   66,  128,   72,  133,  106,   62,  141,
       72,  107,  114,   62,   72,  131,  134,  130,  108,   72,
      138,  109,   72,  110,  135,  111,  139,   72,   72,   72,
      137,  133,  142,  106,   62,   72,   72,  107,  114,   62,
      131,  134,  140,  108,   72,  138,  109,  144,  110,  135,
      111,  139,   72,  143,   72,   72,  137,  147,  142,   72,
      145,   72,  146,  148,  152,   72,  149,  140,  150,  153,

      151,  176,  144,   72,   72,  154,   72,   72,  143,   72,
       72,   72,  147,   72,   72,   72,  145,   72,  146,  148,
      152,  149,   72,  150,  153,  151,  176,  155,   72,  155,
       72,  154,  156,  157,  157,  115,  115,  115,  115,  116,
      116,  158,  159,  159,  162,  122,  122,  114,  123,  168,
      114,  163,  164,  164,  126,  167,  167,  170,  171,  174,
      169,   72,  172,  193,  193,  173,  177,  178,   72,   72,
      175,   72,   72,  114,   72,  168,  114,   72,   72,   72,
       72,  185,  170,  171,  181,  174,  169,  172,   72,   72,
      173,  182,  177,  178,  179,  175,  183,  186,  180,   72,

      184,  196,   72,  189,  187,   72,   72,  185,   72,  188,
      181,   72,  160,   72,  161,  161,  182,   72,   72,   72,
      179,  183,   72,  186,  180,  184,  196,   72,  189,  187,
      190,  157,  157,   72,  198,  188,  191,  192,  192,  158,
      158,  158,  158,  159,  159,  163,  163,  163,  163,  164,
      164,  194,  195,  195,  197,   72,  199,  200,  202,  201,
      198,  203,   72,  114,   72,   72,   72,   72,  204,   72,
      205,  208,  209,  191,  191,  191,  193,  193,  206,  197,
       72,  199,  200,   72,  202,  201,  203,   72,   72,  114,
      207,   72,   72,   72,  204,  210,  205,  208,  209,  213,

       72,  211,  214,  206,  191,  192,  192,  194,  194,  194,
      194,  195,  195,   72,  212,  207,   72,  216,  215,  114,
       72,  210,  114,   72,   72,  213,  211,  217,  214,  219,
      123,  221,  123,  218,  112,  220,   72,   72,  223,  212,
       72,   72,   72,  216,  215,  114,   72,   72,  114,   72,
      222,   72,   72,  217,  224,  219,  221,   72,  218,  225,
      220,  226,   72,  223,   72,   72,   72,   72,   72,   72,
      119,  112,  112,   54,   72,  222,   68,   67,   56,  224,
       54,  227,   72,  227,  225,  227,  227,  226,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   55,  227,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   69,   69,   69,   69,   69,   69,
      101,  101,  101,  101,  102,  227,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  103,  227,  227,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  113,
      227,  227,  227,  113,  227,  113,  125,  125,  125,  125,
      165,  165,  165,  124,  124,  124,  124,  166,  166,  166,
      166,    7,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227
    } ;

static yyconst flex_int16_t yy_chk[763] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    5,    5,    6,    6,   18,   34,   18,   18,
       18,   19,   20,   37,   20,   20,   20,   23,   23,   34,
      226,   38,   19,   37,   41,   19,   20,   63,   19,   63,

       26,  224,   34,   26,   58,   28,   27,  119,   37,  119,
      119,   28,   38,   26,    5,   27,    6,   38,   19,   41,
       41,   19,   20,   28,   19,   26,   31,   27,   26,   29,
       58,   28,   27,   30,   29,   30,   28,    3,    4,   31,
       27,   35,   33,  223,   31,   79,   29,   36,   30,   33,
       39,   31,   31,   35,   79,   29,  221,   36,   30,   29,
       30,  219,   33,  218,   31,  217,   35,   36,   33,   31,
       79,   39,   40,   36,   33,   71,   39,  211,   40,  209,
       40,   75,   36,   42,   42,   71,   40,   59,   59,   59,
       40,   42,   60,   60,   60,   64,   64,   64,   40,   59,

       71,   42,  208,   40,  201,   40,   75,   75,   70,   42,
       42,   40,  199,   62,   85,   62,   42,   53,   62,   62,
       62,   73,   85,  197,   65,   59,   65,   65,   65,   66,
       70,   66,   66,   66,   70,  196,   76,   53,   65,   85,
       73,   53,  126,   66,  188,   74,   77,   73,   53,   76,
       81,   53,   77,   53,   78,   53,   82,   74,  186,   78,
       80,   76,   86,   53,   65,   81,   82,   53,  126,   66,
       74,   77,   83,   53,  185,   81,   53,   90,   53,   78,
       53,   82,   80,   87,   86,   83,   80,   92,   86,   90,
       91,   87,   91,   93,   98,   92,   95,   83,   96,   99,

       97,  139,   90,   95,  184,  100,  139,   99,   87,   96,
       97,   98,   92,  182,   93,   91,   91,  181,   91,   93,
       98,   95,  100,   96,   99,   97,  139,  114,  174,  114,
      171,  100,  114,  114,  114,  115,  115,  115,  116,  116,
      116,  118,  118,  118,  120,  120,  120,  115,  166,  129,
      116,  122,  122,  122,  127,  127,  127,  131,  132,  136,
      130,  151,  133,  160,  160,  135,  140,  141,  132,  147,
      138,  133,  131,  115,  129,  129,  116,  130,  135,  138,
      136,  149,  131,  132,  145,  136,  130,  133,  141,  140,
      135,  145,  140,  141,  144,  138,  146,  150,  144,  143,

      148,  168,  149,  154,  152,  168,  145,  149,  146,  153,
      145,  154,  161,  148,  161,  161,  145,  144,  150,  152,
      144,  146,  142,  150,  144,  148,  168,  153,  154,  152,
      155,  155,  155,  137,  170,  153,  157,  157,  157,  158,
      158,  158,  159,  159,  159,  163,  163,  163,  164,  164,
      164,  167,  167,  167,  169,  170,  172,  173,  176,  175,
      170,  177,  134,  167,  172,  173,  128,  169,  178,  177,
      179,  187,  189,  191,  191,  191,  193,  193,  180,  169,
      175,  172,  173,  176,  176,  175,  177,  178,  180,  167,
      183,  179,  187,  189,  178,  198,  179,  187,  189,  203,

      183,  200,  204,  180,  192,  192,  192,  194,  194,  194,
      195,  195,  195,  200,  202,  183,  203,  206,  205,  194,
      198,  198,  195,  204,  202,  203,  200,  207,  204,  212,
      125,  214,  124,  210,  113,  213,  101,   94,  216,  202,
      205,  214,  206,  206,  205,  194,  210,  213,  195,  207,
      215,  212,  216,  207,  220,  212,  214,  215,  210,  222,
      213,  225,   89,  216,   88,   84,   72,  220,   69,  222,
       61,   56,   55,   54,   32,  215,   25,   21,   12,  220,
        9,    7,  225,    0,  222,    0,    0,  225,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,

      229,  229,  229,  229,  229,  229,  229,  229,  229,  229,
      229,  229,  230,    0,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  231,  231,  231,  231,  231,  231,
      232,  232,  232,  232,  233,    0,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  234,    0,    0,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  236,
        0,    0,    0,  236,    0,  236,  237,  237,  237,  237,
      238,  238,  238,  239,  239,  239,  239,  240,  240,  240,
      240,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lecticalAnalyser.l"
/*Flex file to implement lectical analyser for pasc500.*/
/*Authors: Mizaras Fokion(2574), Pantazi-Kypraiou Maria(2596), Poulianou Xaidw(2613)*/
/*Date: 25/11/2020 */
/* Libraries, declaration of variables and functions' prototypes. */
#line 10 "lecticalAnalyser.l"
	#include <stdio.h>
	#include <string.h>
	#include <stdlib.h>
	#include <math.h>
	#define MAX_SIZE 100
	#define MAX_ERRORS 5
	#define MAX_LINE_SIZE 100
	// #include "tokens.h"

	#include "syntaxAnalyser.tab.h"

	// Flag for EOF. 
	int eof = 0;

	// Counter for lines.
	int lines = 1;

	// Counter for errors. When MAX_ERRORS (= 5) is reached program terminates.
	int errors = 0;

	// Buffer to store strings.
	char str_buffer[MAX_SIZE];
	char *str_ptr;

	// Buffer to store whole input line to print in case of error.
	extern char line_buffer[MAX_LINE_SIZE];

	extern void yyerror(const char *message);	
	// File descriptor to opening file.
	extern FILE* yyin;
	extern FILE* yyin2;
	//FILE* fd_help;

	void error_line();

	// yytext conversion from string to int
	int dec_to_int(char* str);
	int hex_to_int(char* str);
	int bin_to_int(char*str);

	// yytext conversion from string to int
	double dec_to_real(char* str);
	double hex_to_real(char* str);
	double bin_to_real(char*str);
/************* ICONST VALUES *************/
/************* RCONST VALUES *************/
/************* CCONST VALUES *************/


/************* KEYWORD VALUES *************/
#line 769 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRINGS 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 78 "lecticalAnalyser.l"

#line 991 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 228 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 692 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 79 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_PROGRAM, lines);
	                    yylval.strval = strdup(yytext); return T_PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_PROCEDURE, lines);
	                    yylval.strval = strdup(yytext); return T_PROCEDURE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_CONST, lines);
                    	yylval.strval = strdup(yytext); return T_CONST;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_CHAR, lines);
	                    yylval.strval = strdup(yytext); return T_CHAR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_ARRAY, lines);
	                    yylval.strval = strdup(yytext); return T_ARRAY;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_SET, lines);
	                    yylval.strval = strdup(yytext); return T_SET;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_OF, lines);
	                    yylval.strval = strdup(yytext); return T_OF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 94 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_RECORD, lines);
	                    yylval.strval = strdup(yytext); return T_RECORD;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_REAL, lines);
	                    yylval.strval = strdup(yytext); return T_REAL;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_READ, lines);
	                    yylval.strval = strdup(yytext); return T_READ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_VAR, lines);
	                    yylval.strval = strdup(yytext); return T_VAR;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_FORWARD, lines);
	                    yylval.strval = strdup(yytext); return T_FORWARD;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 104 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_FOR, lines);
	                    yylval.strval = strdup(yytext); return T_FOR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_FUNCTION, lines);
	                    yylval.strval = strdup(yytext); return T_FUNCTION;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 109 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_INTEGER, lines);
                    	yylval.strval = strdup(yytext); return T_INTEGER;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 111 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_IF, lines);
	                    yylval.strval = strdup(yytext); return T_IF;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 113 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_BOOLEAN, lines);
	                    yylval.strval = strdup(yytext); return T_BOOLEAN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_BEGIN, lines);
	                    yylval.strval = strdup(yytext); return T_BEGIN;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 117 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_END, lines);
	                    yylval.strval = strdup(yytext); return T_END;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 119 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_ELSE, lines);
	                    yylval.strval = strdup(yytext); return T_ELSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 121 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_THEN, lines);
	                    yylval.strval = strdup(yytext); return T_THEN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 124 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_TO, lines);
	                    yylval.strval = strdup(yytext); return T_TO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_TYPE, lines);
	                    yylval.strval = strdup(yytext); return T_TYPE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 128 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_WRITE, lines);
	                    yylval.strval = strdup(yytext); return T_WRITE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 130 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_WHILE, lines);
	                    yylval.strval = strdup(yytext); return T_WHILE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 132 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_WITH, lines);
	                    yylval.strval = strdup(yytext); return T_WITH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 134 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_DO, lines);
	                    yylval.strval = strdup(yytext); return T_DO;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 136 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_DOWNTO, lines);
	                    yylval.strval = strdup(yytext); return T_DOWNTO;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 139 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_BCONST, lines);
	                    yylval.strval = strdup(yytext); return T_BCONST;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 141 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_BCONST, lines);
	                    yylval.strval = strdup(yytext); return T_BCONST;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 143 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_OROP, lines);
	                    yylval.strval = strdup(yytext); return T_OROP;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 145 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_NOTOP, lines);
	                    yylval.strval = strdup(yytext); return T_NOTOP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 147 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_MULDIVANDOP, lines);
	                    yylval.strval = strdup(yytext); return T_MULDIVANDOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 149 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_MULDIVANDOP, lines);
	                    yylval.strval = strdup(yytext); return T_MULDIVANDOP;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 151 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_MULDIVANDOP, lines);
	                    yylval.strval = strdup(yytext); return T_MULDIVANDOP;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 153 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_INOP, lines);
	                    yylval.strval = strdup(yytext); return T_INOP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 156 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_ID, lines);
	                    yylval.strval = strdup(yytext); return T_ID;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 158 "lecticalAnalyser.l"
{printf("yytext = %s => %lf and token = %d in line %d\n", yytext, dec_to_real(yytext), T_RCONST, lines);
	                    yylval.doubleval = dec_to_real(yytext); return T_RCONST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 160 "lecticalAnalyser.l"
{printf("yytext = %s =>% lf and token = %d in line %d\n", yytext, dec_to_real(yytext), T_RCONST, lines);
	                    yylval.doubleval = dec_to_real(yytext); return T_RCONST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 162 "lecticalAnalyser.l"
{printf("yytext = %s => %lf and token = %d in line %d\n", yytext, bin_to_real(yytext), T_RCONST, lines);
	                    yylval.doubleval = bin_to_real(yytext); return T_RCONST;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 164 "lecticalAnalyser.l"
{printf("yytext = %s => %lf and token = %d in line %d\n", yytext, hex_to_real(yytext), T_RCONST, lines);
	                    yylval.doubleval = hex_to_real(yytext); return T_RCONST;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 166 "lecticalAnalyser.l"
{printf("yytext = %s => %d and token = %d in line %d\n", yytext, dec_to_int(yytext) , T_ICONST, lines);
	                    yylval.intval = dec_to_int(yytext); return T_ICONST;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 168 "lecticalAnalyser.l"
{printf("yytext = %s => %d and token = %d in line %d\n", yytext, bin_to_int(yytext) , T_ICONST, lines);
	                    yylval.intval = bin_to_int(yytext); return T_ICONST;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 170 "lecticalAnalyser.l"
{printf("yytext = %s => %d and token = %d in line %d\n", yytext, hex_to_int(yytext) , T_ICONST, lines);
	                    yylval.intval = hex_to_int(yytext); return T_ICONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 172 "lecticalAnalyser.l"
{printf("yytext = %s and token = %d in line %d\n", yytext,   T_CCONST, lines);
	                    yylval.strval = strdup(yytext); return T_CCONST;}
	YY_BREAK
/************* OPERATOR VALUES *************/
case 46:
YY_RULE_SETUP
#line 177 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_MULDIVANDOP, lines);
	                    yylval.strval = strdup(yytext); return T_MULDIVANDOP;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 180 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_RELOP, lines);
	                    yylval.strval = strdup(yytext); return T_RELOP;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 182 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_ADDOP, lines);
	                    yylval.strval = strdup(yytext); return T_ADDOP;}
	YY_BREAK
/************* OTHER VERBAL UNITS VALUES *************/						
case 49:
YY_RULE_SETUP
#line 187 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_LPAREN, lines);
	                    yylval.strval = strdup(yytext); return T_LPAREN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 189 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_RPAREN, lines);
	                    yylval.strval = strdup(yytext); return T_RPAREN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 191 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_SEMI, lines);
	                    yylval.strval = strdup(yytext); return T_SEMI;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 193 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_DOTDOT, lines);
                        yylval.strval = strdup(yytext); return T_DOTDOT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 195 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_DOT, lines);
	                    yylval.strval = strdup(yytext); return T_DOT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 197 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_COMMA, lines);
	                    yylval.strval = strdup(yytext); return T_COMMA;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 199 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_ASSIGN, lines);
	                    yylval.strval = strdup(yytext); return T_ASSIGN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 201 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_EQU, lines);
	                    yylval.strval = strdup(yytext); return T_EQU;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 203 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_COLON, lines);
	                    yylval.strval = strdup(yytext); return T_COLON;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 205 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_LBRACK, lines);
	                    yylval.strval = strdup(yytext); return T_LBRACK;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 207 "lecticalAnalyser.l"
{printf("yytext = %s  and token = %d in line %d\n", yytext,   T_RBRACK, lines);
	                    yylval.strval = strdup(yytext); return T_RBRACK;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 209 "lecticalAnalyser.l"
{if(!eof){error_line();} lines++;}
	YY_BREAK
/*
<INITIAL><<EOF>> 		{printf("EOF FOUND with token = %d in line %d\n", T_EOF, lines);
	                    return T_EOF;}*/
/************* STATE FOR STRINGS AND SUBCASES *************/
case 61:
YY_RULE_SETUP
#line 216 "lecticalAnalyser.l"
{str_ptr = str_buffer; BEGIN(STRINGS);}
	YY_BREAK
case YY_STATE_EOF(STRINGS):
#line 217 "lecticalAnalyser.l"
{yyerror("Unterminated string"); yyterminate();}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 218 "lecticalAnalyser.l"
{BEGIN(INITIAL); *str_ptr = '\0'; 
                        printf("String = %s  and token = %d in line %d\n", str_buffer,  T_STRINGS, lines);return T_STRINGS;}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 220 "lecticalAnalyser.l"
yyerror("Newline in string");
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 221 "lecticalAnalyser.l"
*str_ptr++ = '\n';
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 222 "lecticalAnalyser.l"
*str_ptr++ = '\t';
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 223 "lecticalAnalyser.l"
*str_ptr++ = '\v';
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 224 "lecticalAnalyser.l"
*str_ptr++ = '\f';
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 225 "lecticalAnalyser.l"
*str_ptr++ = '\r';
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 226 "lecticalAnalyser.l"
*str_ptr++ = '\b';
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 227 "lecticalAnalyser.l"
{if(!eof){error_line();} lines++;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "lecticalAnalyser.l"
{char *helper = yytext;
						while(*helper){
							*str_ptr++ = *helper++;
						}}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 233 "lecticalAnalyser.l"
*str_ptr++ = yytext[1];
	YY_BREAK
/************* STATE FOR COMMENTS AND SUBCASES *************/
case 73:
YY_RULE_SETUP
#line 237 "lecticalAnalyser.l"
BEGIN(COMMENT);
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 238 "lecticalAnalyser.l"
{yyerror("Unterminated comment"); yyterminate();}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 239 "lecticalAnalyser.l"
{printf("COMMENT FOUND\n");}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 240 "lecticalAnalyser.l"
{if(!eof){error_line();} lines++;printf("COMMENT FOUND\n");}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 242 "lecticalAnalyser.l"
BEGIN(INITIAL);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 244 "lecticalAnalyser.l"
{}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 245 "lecticalAnalyser.l"
yyerror("Illegal token");
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 247 "lecticalAnalyser.l"
ECHO;
	YY_BREAK
#line 1525 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 228 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 228 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 227);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 247 "lecticalAnalyser.l"



// Function to increase number of errors, when found, and print the corresponding line.
// void yyerror(char* message){
// 	errors++;
// 	printf("(#%d) errors \"%s\" at token  in line (%d): %s\n", errors, message, lines, line_buffer);
// 	if(errors == MAX_ERRORS){
// 		printf("MAX ERRORS detected!");
// 		exit(-1);
// 	}
// }

// Function to store most recent line in "line_buffer".
void error_line(){
	char c;
	int i;

	for(i = 0; i < MAX_LINE_SIZE; i++){
		line_buffer[i] = '\0';
	}

	i = 0;
	while(1){
		c = fgetc(yyin2);
		if(feof(yyin2) || c == '\n'){
			break;
		}
		line_buffer[i] = c;
		i++;
	}

	if(feof(yyin2)){
		eof = 1;
	}
}

// INT
int dec_to_int(char* str){
	return(atoi(str));
}
int hex_to_int(char* str){
	return((int)strtol(&str[2], NULL, 16));
}
int bin_to_int(char* str){
	return((int)strtol(&str[2], NULL, 2));
}

// REAL
double dec_to_real(char* str){
  return atof(str);
}
double hex_to_real(char* str){
	double res;
	int i, length_real;
	char* c;
	
	c = strchr(str, '.');
	length_real = strlen(c) - 1;
	res = (int)strtol(&str[2], &c, 16);

	for(i = 1; i <= length_real; i++){
		if(c[i] > '9' && c[i] < 'G')
			res = (c[i] - 'A')*(1/pow(16, i)) + res;
		else
			res = (c[i] - '0')*(1/pow(16, i)) + res;
	}

	return(res);
}
double bin_to_real(char* str){
	double res;
	int i, length_real;
	char *c;
	
	c = strchr(str, '.');
    length_real = strlen(c) - 1;
	res = (int)strtol(&str[2],  &c, 2);
	for(i = 1; i <= length_real; i++){
		res = (c[i] - '0')*(1/pow(2, i)) + res;
	}

	return(res);
}

// Main function that opens the file(given as argument) and reads it until EOF or MAX_ERRORS.
// int main(int argc, char* argv[]){
// 	int token;

// 	if(argc < 2){
// 		printf("No file given!");
// 		return(0);
// 	}

// 	fd = fopen(argv[1], "r");
	
// 	if(fd == NULL){
// 		perror("fopen");
// 		return -1;
// 	}
// 	fd_help = fopen(argv[1], "r");
// 	if(fd_help == NULL){
// 		perror("fopen");
// 		return -1;
// 	}
// 	error_line();
// 	yyset_in(fd_help);
// 	do{	
// 	 	token = yylex();
// 	} while(token != T_EOF);
    
// 	fclose(fd);
// 	fclose(fd_help);
// 	yyterminate();


// 	return(0);
// }


